# Generated by Django 4.2.1 on 2023-09-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.CharField(default='new', max_length=50),
            preserve_default=False,
        ),
    ]
