# Generated by Django 4.2.1 on 2023-09-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_products_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='offer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='caetgory',
            field=models.ManyToManyField(to='coreapp.category'),
        ),
    ]
