# Generated by Django 4.2.1 on 2023-09-02 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_category_alter_products_offer_products_caetgory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='caetgory',
            new_name='categories',
        ),
    ]
